### ISSUE TITLE
test site build fails, but publishing on staging site runs fine

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/monal-im.org#54]
Something is odd, this github action fails with my newest blogpost commit while the publishing github action still runs through: https://github.com/monal-im/monal-im.org/actions/runs/8494401147/job/23269572965

**Comment by wiseweb-works** [comment]
Yes, I got a notification via E-mail. I will check. 👍🏻

**Comment by tmolitor-stud-tu** [comment]
oh wow, a lot of problems :(

do you need any help from me regarding these?

**Comment by wiseweb-works** [comment]
I have a great idea if we want to solve the workflow problem first and then fix the remaining parts one by one.

If I give the `--baseURL` parameter to the command in [this section](https://github.com/monal-im/monal-im.org/blob/00163a5330258eef048620ad0c6c5c1d66d5cecc/.github/workflows/buildSite.yml#L28C9-L28C27), it will not give any error output. At the same time, it will not cause a compatibility problem with the `serve` parameter.

**Comment by tmolitor-stud-tu** [comment]
we can squash all commits into one while merging the pr, does that help? :)

**Comment by wiseweb-works** [comment]
Normally that would make sense. But after that we need to still delete [ExpectedCommaWorkflow.yml](https://github.com/monal-im/monal-im.org/blob/54-test-site-build-fails/.github/workflows/expectedCommaWorkflow.yml) (created for test) and change the parameter in your [buildSite.yml](https://github.com/monal-im/monal-im.org/blob/staging/.github/workflows/buildSite.yml) file. That's why I proposed to change the code in place instead of squashing commits.

Should I use 
https://monal-im.org or 
https://monal-im.github.io/monal-im.org as `--baseURL` parameter in workflows?

**Comment by tmolitor-stud-tu** [comment]
You could add even one commit more deleting these files again, but sure, you can commit it directly, too :)

Since the deployment on the main website is run on directly on these servers, the workflow should use https://monal-im.github.io/monal-im.org

@FriedrichAltheide could you please change that on our two servers as well?
