### ISSUE TITLE
Create workflow with timer

### ISSUE THREAD

**Issue by tmolitor-stud-tu** [monal-im/monal-im.org#75]
Create a workflow with a timer to compile the staging and production websites once a day. This will update the supported xeps list, translation status image etc.

**Comment by wiseweb-works** [comment]
I've seen it, I'm working on it. 👍🏻 @tmolitor-stud-tu

**Comment by wiseweb-works** [comment]
Update: The problem was that if Github runs too many Actions in the same time interval (across all github), it ignores scheduled tasks in some repos or starts them later than the specified time. 

5-min-actions (which I had set up for testing), only ran a couple of times until noon. To solve this, it was necessary to choose a time that is generally less preferred. I hope our current time preference is better.

**Comment by tmolitor-stud-tu** [comment]
Thanks!! :)
